### ISSUE TITLE
Combining WAI and Yesod instrumentation loses exception details

### ISSUE THREAD

**Issue by spencerjanssen** [iand675/hs-opentelemetry#102]
I've got an application instrumented with both hs-opentelemetry-instrumentation-wai and hs-opentelemetry-instrumentation-yesod.  For the most part this works well, however I've found that the details of exceptions (exception message, exception backtrace, span status message) thrown by handlers never make it to WAI middleware trace.

I see why this happens: by default Yesod catches the exception and converts it to an error page -- the WAI instrumentation never sees the exception.  However, I'm not sure what the proper fix is.  The Yesod middleware could simply `recordException` targeting the WAI trace.  Unfortunately this still results in the WAI middleware setting a `""` span status message rather than a  meaningful description.

**Comment by pbrisbin** [comment]
Hi there, I'm bumping into this currently.

>  The Yesod middleware could simply `recordException` targeting the WAI trace.

Based on my limited understanding, I think this may be the only option here.

>  Unfortunately this still results in the WAI middleware setting a `""` span status message rather than a meaningful description.

Can it not also use `setStatus` to address this?

I'm picturing something like...

```hs
instance Yesod App where
  -- ...

  yesodMiddleware h = h `onException` \ex -> do
    req <- waiRequest
    for_ (lookupSpan =<< requestContext req) $ \span -> do
      recordException span mempty Nothing ex
      setStatus span $ Error $ pack $ displayException ex
```
