### ISSUE TITLE
In-memory Processor for testing

### ISSUE THREAD

**Issue by shlevy** [iand675/hs-opentelemetry#105]
For the testsuite of [e11y-otel](https://hackage.haskell.org/package/e11y-otel), I ended up writing an `MVar [ImmutableSpan]`-backed `Processor` to inspect the generated spans. It would be nice if something like this were available upstream, presumably more polished and with a cleaner interface.

https://github.com/shlevy/e11y/blob/50069849193a3199c1f78d6687d76fe1521f8e02/e11y-otel/test/Test.hs#L84-L97

**Comment by iand675** [comment]
Isn’t that basically this? https://hackage.haskell.org/package/hs-opentelemetry-exporter-in-memory

**Comment by shlevy** [comment]
Oops, yes, thanks!
