### ISSUE TITLE
Conflict marker in `hs-opentelemetry-utils-exceptions.cabal`

### ISSUE THREAD

**Issue by develop7** [iand675/hs-opentelemetry#108]
https://github.com/iand675/hs-opentelemetry/blob/54251bd15565e3a07cda0cecfa544d209ae63df6/utils/exceptions/hs-opentelemetry-utils-exceptions.cabal#L1-L9

This renders the `.cabal` file unusable. 

I mean, come on, man.

**Comment by ocharles** [comment]
> I mean, come on, man.

This is unnecessary and demotivating to people who are just doing their best. Mistakes happen, and I suggest you reconsider that comment.

This is in the process of being fixed at https://github.com/iand675/hs-opentelemetry/pull/107

**Comment by develop7** [comment]
> This is unnecessary and demotivating to people who are just doing their best. Mistakes happen, and I suggest you reconsider that comment.

Mistakes happen indeed, and this comment of mine was the one. I sincerely apologize to anyone might be hurt by my comment and promise I will make sure this won't happen again.

**Comment by develop7** [comment]
> This is in the process of being fixed at #107

It's merged, so closing. Thank you for heads up.
