### ISSUE TITLE
Improving project stewardship

### ISSUE THREAD

**Issue by iand675** [iand675/hs-opentelemetry#110]
I've been feeling lately that I'm not necessarily responding to issues, PRs, and upstream evolutions of the OpenTelemetry spec in a timely fashion.

My desire for this project has been to build tracing that is fast, stable, relatively easy to use, and that supports most popular Haskell libraries. Ultimately, I'd like to contribute the library to the OpenTelemetry project itself. However, I've both had a new baby and had my oldest child pass away suddenly in the past year, so I have very little time or motivation to really work on anything outside of what is needed on this project to support the company that I work for.

So, I'd like to bring on one or two more people as core owners / contributors that will feel empowered to make decisions and shepherd the project into becoming mature enough that it becomes a go-to tool for production Haskell users. If you are interested, please let me know, and we can figure out next steps.

**Comment by iand675** [comment]
Tagging a few people here that have previously contributed: @kakkun61 @solomon-b @ocharles @claymager

**Comment by solomon-b** [comment]
Hi @iand675. I am so sorry for your loss I can't imagine what you are going through. 

I have the same desires for Haskell OpenTelemetry support. I don't think I have the bandwidth to do a lot of major feature work but I could help with code reviews, generating more regular maintenance releases, and the occasional feature work.

**Comment by ocharles** [comment]
I'd like to echo @solomon-b - that sounds like an incredibly difficult situation, and I'd love to do what I can to help. You've done a great job with this library and we use it production at CircuitHub, so I'd like to give back. I'm not deeply involved with OpenTelemetry, but I'm happy to join as a maintainer to help keep things ticking along and building. Feel free to add me both here and on Hackage and I'll do what I can!

**Comment by kakkun61** [comment]
Hello😊 I am working to make additional instrumentations at HERP's request. HERP is one of the companies that sponsor the Haskell Foundation. HERP is already using hs-opentelemetry on a production environment.

I would like to support this project.

**Comment by velveteer** [comment]
Hey Ian, I am also willing to help maintain this library. We are using it at H-E-B and we really like it.

**Comment by develop7** [comment]
First of all let me express late condolences and, yeah, I cannot possibly grasp the idea of what are you going through. I'm working on integrating OTel into PostgREST and would like to offer my help co-maintaining the project as well.

**Comment by michaelpj** [comment]
HI Ian. I'd also like to volunteer to help maintain. I can at least get started by doing some code reviews. But at the moment I'm not sure who apart from Ian has commit rights? Or publish rights for the Hackage packages?

**Comment by pbrisbin** [comment]
Hi everyone, I can tell I'm not the only one who feels terribly for Ian and is looking to help any way I can. It seems to me that we're all a bit stalled on _some_ action that Ian would have to take to grant some kind of access here and/or on Hackage. I wonder if it's time to fork this repository and consider a process with the Hackage Admins to take over the packages. Not in any kind of hostile way, of course, but just so that we can all take on this load without requiring even a small effort from Ian during this time.

What does everyone think?

Ian, if you reply that this is against your wishes (no reason or explanation needed), I will drop the idea.

**Comment by michaelpj** [comment]
Hi all.

I messaged Ian and he's given me commit access. So I can approve and merge PRs (amusingly I can't approve my own PRs :sweat_smile: ). I will try and make some headway on the PR backlog.

We don't have Hackage rights yet, but for the time being I hope people can get by with `source-repository-package` stanzas.

**Comment by iand675** [comment]
Hi all, I'm very sorry for the delay in responding to this. Here are the people I currently want to entrust GitHub / Hackage maintainership of the project. I'll try to ensure you all have permissions to maintain GitHub & Hackage packages by Friday of this week.

@michaelpj @ocharles @kakkun61 @pbrisbin @velveteer. 

My current goals are that we aim towards:

1. Maintaining compliance with the latest OTel specs. When we update this repo to conform to the latest OTel spec and it involves a departure from prior OTel spec compatibilty, it should involve a major version bump of all related packages.
2. Keeping dependencies as minimal as possible for packages maintained within this repository. Ideally, we'd even reduce it relative to the current set of dependencies. I want package developers to feel totally safe in embedding the `hs-opentelemetry-api` package and instrumenting with it without feeling like it will break in the future. 
3. Ensuring backwards compatibility with existing users of the hs-opentelemetry-* offiical packages. My goal here is that we support as far backwards/forwards as possible such that users are able to upgrade without worrying about their alerting systems breaking.
4. Unity. There are at least 5 commercial consumers of the project at this point, so I want to make sure that this project facilitates commercial success for the Haskell ecosystem as a whole. If I feel that a contributor is detracting from this goal, I reserve the right to remove them as a contributor.

**Comment by michaelpj** [comment]
Thanks Ian!

**Comment by pbrisbin** [comment]
Thank you!

**Comment by ocharles** [comment]
Thanks @iand675, and no worries about the delay! I am more than happy with the plan you've outlined. When you get time, just add me to this repo and Hackage, and we'll take care of the rest. Cheers!

**Comment by iand675** [comment]
@ocharles I believe you already are a collaborator on this repo. Is there something else you're hoping for me to do?

**Comment by ocharles** [comment]
Ah yea, I am indeed! I went to merge a PR but I see it just needed an approval review. I think I'm all set on this repo

**Comment by iand675** [comment]
OK, I've added all of the aforementioned people as maintainers to all of the packages in the repo that are on Hackage. Ping me if I've missed any, but I'm going to close out this issue for now and future conversation can go into new issues.
