### ISSUE TITLE
AWS X-Ray propagator(intent to implement)

### ISSUE THREAD

**Issue by belevy** [iand675/hs-opentelemetry#115]
I am interested in implementing a propagator for AWS X-Ray so that request traces can be linked to CloudFront/API Gateway/ALB in X-Ray. 

Is this something that should be implemented in a separate library or committed to this repo? Should there be a contrib namespace/repo to support discovererability?

**Comment by belevy** [comment]
I'm talking about connecting X-Trace-Id to the otel trace/span. I don't see what you specifically are referring to in that folder.

**Comment by iand675** [comment]
oh sorry, totally wrong link. https://hackage.haskell.org/package/hs-opentelemetry-awsxray is what I meant to link to!

**Comment by belevy** [comment]
Oh awesome, that makes my life easier :). I guess this proves my point as to discoverability
