### ISSUE TITLE
Support OTLP 1.x

### ISSUE THREAD

**Issue by mx-psi** [iand675/hs-opentelemetry#119]
Based on the submodule named 'proto' on the top-level folder of this repository, it looks like the OTLP proto definitions are based on open-telemetry/opentelemetry-proto@b43e9b18b76abf3ee040164b55b9c355217151f3, i.e. v0.11.0 from October 2021. This means that the current generated datatypes (those in the 'otlp' folder) reference fields that no longer exist in more recent OTLP versions.

For example, I can find this reference to `IntGauge`:

https://github.com/iand675/hs-opentelemetry/blob/02653bbfa286579be13cef17701da454ac3dfce1/otlp/src/Proto/Opentelemetry/Proto/Metrics/V1/Metrics.hs#L55

which was removed in v0.12.0 (specifically on open-telemetry/opentelemetry-proto/pull/342).

OTLP has since released a stable version, and some OpenTelemetry components no longer support v0.11.0 (e.g. [the OpenTelemetry Collector dropped support for OTLP v0.11.0 in v0.44.0](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#v0440-beta)). In order to make this library work with the rest of the OpenTelemetry ecosystem, it would be necessary to bump the proto definitions

**Comment by iand675** [comment]
Thanks for raising this!

**Comment by michaelpj** [comment]
Fixed in https://github.com/iand675/hs-opentelemetry/pull/150
