### ISSUE TITLE
No way to create links conveniently

### ISSUE THREAD

**Issue by michaelpj** [iand675/hs-opentelemetry#141]
The only way to do it that I can see is:
- Pass `[NewLink]` in when creating a span
- `NewLink` needs a `SpanContext`
- Use `getSpanContext` (not exported from the SDK!) to get the span context earlier

It would be nice to have something like 
```
-- makes a link to the given span
linkTo :: MonadIO m => Span -> Attributes -> m NewLink
-- adds the link to a span
addLink :: MonadIO m => Span -> NewLink -> m ()
```

**Comment by RiugaBachi** [comment]
Hi all, has anyone taken a crack at this yet? I'm interested in making a PR for this as I've encountered similar limitations recently too.

**Comment by ocharles** [comment]
I don't think anyone has started anything here yet @RiugaBachi - feel free to get stuck in!
