### ISSUE TITLE
Is there a way to set up resource attributes?

### ISSUE THREAD

**Issue by geraldus** [iand675/hs-opentelemetry#147]
Hello! I've noticed that adding span attributes (also known as tags) seems straightforward, but I'm having difficulty understanding if there's an approach to configure resource attributes (also known as process tags). In my situation, they are static, determined at startup, and remain consistent across all spans (such as environment, application name, version, etc.).

**Comment by michaelpj** [comment]
I think the SDK honours `OTEL_RESOURCE_ATTRIBUTES`, but I'm not sure if there's a way to set them programmatically, currently.

**Comment by geraldus** [comment]
Thanks, I've already found this out from sources, setting OTEL_RESOURCE_ATTRIBUTES works as expected. Closing this for now.

**Comment by geraldus** [comment]
Resolved
