### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by develop7** [iand675/hs-opentelemetry#154]
Now that the keys are handed over and the hiatus is, hopefully, past us: there's lots of good stuff has been merged since last release on Aug, 31 of 2023 — could today be the a good time to cut a new one? 

For me in particular (as a @postgrest contributor) building `hs-opentelemetry` from a repository requires additional build-time dependency of a protobuf compiler, `protoc`, not to mention Hackage is strongly preferred over VCS checkouts across PostgREST.

**Comment by michaelpj** [comment]
Oh dear, I see the custom setup is new since the previous release. I think we should consider reverting that.

**Comment by michaelpj** [comment]
I've released the packages!

**Comment by develop7** [comment]
On them, thanks, man!
