### ISSUE TITLE
Avoid build-time code generation

### ISSUE THREAD

**Issue by michaelpj** [iand675/hs-opentelemetry#158]
I think we should seriously consider avoiding any build-time code generation. At the moment that's mostly `hs-opentelemetry-otlp`, but there is also https://github.com/iand675/hs-opentelemetry/pull/142 which I think is desirable.

Why?

1. It requires custom setups. Custom setups are generally harder for tooling to deal with, cost you parallelism, etc. The general feeling of the cabal developers is that they wish they didn't exist :joy: 
2. It puts more requirements onto our users. Notably, currently users need to have `protoc` around in order to build `hs-opentelemetry-otlp`. Cabal does not know this, it is quite opaque to users.

There is an easy way to avoid this: just do the codegen manually and check in the result. It's ugly, and involves checking in generated code, but it's robust and not too painful if the input doesn't change that often (which I don't think it does).

I also note that the last release of `hs-opentelemetry-otlp` did _not_ use a custom setup, so this is going to be a new breaking requirement for our users. We [already](https://github.com/iand675/hs-opentelemetry/issues/154#issue-2633250118) have people complaining about that.

Overall, I would prefer to revert https://github.com/iand675/hs-opentelemetry/pull/122 before we release, and ideally commit to not doing this in the future.

cc @iand675 and @evanlauer1 , who are likely to have opinions.

**Comment by michaelpj** [comment]
@marinelli has a PR up reverting to checked in generated code. I'll leave it a while in case anyone has any objections, otherwise I'll merge that.

**Comment by develop7** [comment]
> There is an easy way to avoid this: just do the codegen manually and check in the result. It's ugly, and involves checking in generated code, but it's robust and not too painful if the input doesn't change that often (which I don't think it does).

Did a quick glance at https://github.com/open-telemetry/opentelemetry-proto/commits/main/ and it gets updated every few months or so, which doesn't seem often enough to warrant a custom setup.

**Comment by michaelpj** [comment]
We're back to manual generation for now.
