### ISSUE TITLE
Why are the `outboundCarrier`s for `Propagator`s usually `ResponseHeaders`?

### ISSUE THREAD

**Issue by danidiaz** [iand675/hs-opentelemetry#160]
[`Propagator`](https://hackage.haskell.org/package/hs-opentelemetry-api-0.1.0.0/docs/OpenTelemetry-Propagator.html#t:Propagator)s have `inboundCarrier`s for extraction and `outboundCarrier`s for injection. 

```
data Propagator context inboundCarrier outboundCarrier = Propagator
  { propagatorNames :: [Text]
  , extractor :: inboundCarrier -> context -> IO context
  , injector :: context -> outboundCarrier -> IO outboundCarrier
  }
```

In the implementations I've looked at [1](https://hackage.haskell.org/package/hs-opentelemetry-propagator-w3c-0.0.1.3/docs/OpenTelemetry-Propagator-W3CTraceContext.html#v:w3cTraceContextPropagator) [2](https://hackage.haskell.org/package/hs-opentelemetry-propagator-b3-0.0.1.1/docs/OpenTelemetry-Propagator-B3.html#v:b3TraceContextPropagator) [3](https://hackage.haskell.org/package/hs-opentelemetry-propagator-datadog-0.0.0.0/docs/OpenTelemetry-Propagator-Datadog.html#v:datadogTraceContextPropagator), the `outboundCarrier` is usually [`ResponseHeaders`](https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types-Header.html#t:ResponseHeaders).

I might be misunderstanding how propagators work, but shouldn't the `outboundCarrier`s be [RequestHeaders](https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types-Header.html#t:RequestHeaders), just like the `inboundCarrier`s are? When we perform a request, we inject the context information into the request headers. I don't think response headers play any part.

(It doesn't matter in practice though, because `RequestHeaders` and `ResponseHeaders` are type synonyms for the same type. But it might induce some confusion when reading the Haddocks.)

**Comment by michaelpj** [comment]
I think you're right. Could you make a PR/
