### ISSUE TITLE
hs-opentelemetry-propagator-datadog upload rights

### ISSUE THREAD

**Issue by michaelpj** [iand675/hs-opentelemetry#167]
Hi @kakkun61 , could you please add the same set of people as uploaders for `hs-opentelemetry-propagator-datadog` as for the other packages? I can't upload a new version of it, so I can't release the `hs-opentelemetry-api` version that depends on it.

**Comment by michaelpj** [comment]
In fact, it's worse than that, I thought I could upload it, so I've already uploaded a now-broken version of `hs-opentelemetry-sdk`...

**Comment by kakkun61** [comment]
@michaelpj Tentatively I added michaelpj.

**Comment by michaelpj** [comment]
Thanks, I was able to release it. Possibly other people should be able to as well, though.
