### ISSUE TITLE
Figure out how to get library versions without hardcoding them

### ISSUE THREAD

**Issue by iand675** [iand675/hs-opentelemetry#2]

**Comment by hw202207** [comment]
One option is to get from generated `Paths_` module.

```
import Paths_${package_name} (version)
```

It has type [Version](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Version.html#t:Version)

**Comment by iand675** [comment]
Unfortunately that only works if the package explicitly exports it.

**Comment by freizl** [comment]
> Unfortunately that only works if the package explicitly exports it.

Curious what's the problem with this?

Looks like we could leave in `other-module` and it wont be public (haddock document)?
e.g. https://github.com/tekul/jose-jwt/blob/master/jose-jwt.cabal#L47

**Comment by hw202207** [comment]
nvm. it doesn't work unless there is `{-# OPTIONS_HADDOCK prune #-}` in the module.

**Comment by iand675** [comment]
I think maybe the aim of this wasn't explained well enough when I created this issue.

The goal is this:

For libraries that we write instrumentation for (Yesod, persistent, etc.), it would be nice to know what version of things like `yesod-core` that we are running against when debugging an issue in production. As far as I can tell, those libraries would have to be altered to export their `Paths_` module so that we would have access to that information. In the long-term, it would be really nice to have the `hs-opentelemetry` suite of packages become stable enough and trusted enough that these libraries feel comfortable integrating directly or making changes to make us happy, but in the meantime it's a little challenging to get at this information.

**Comment by hw202207** [comment]
Aha.. I see what's meaning now. Thanks!

I learned there is cabal command to [list all installed packages](https://cabal.readthedocs.io/en/3.8/cabal-commands.html#cabal-list). Not sure if it could be short term hacky solution.

**Comment by mmhat** [comment]
You can simply use something like this:
```haskell
{-# LANGUAGE CPP #-}

yesodVersionString :: String
yesodVersionString = VERSION_yesod
```

**Comment by michaelpj** [comment]
I have a nice little TH helper for this that I should upstream.

**Comment by michaelpj** [comment]
https://github.com/iand675/hs-opentelemetry/pull/161
