### ISSUE TITLE
Code Formatter

### ISSUE THREAD

**Issue by kakkun61** [iand675/hs-opentelemetry#29]
I think formatting codes with a code formatter is better.

- Introduce a code formatter?
- Which code formatter?
  - [stylish-haskell](https://github.com/haskell/stylish-haskell)
  - [ormolu](https://github.com/tweag/ormolu)
  - [fourmolu](https://github.com/fourmolu/fourmolu)
  - etc.

**Comment by kakkun61** [comment]
@iand675 Which you prefer?

**Comment by iand675** [comment]
@kakkun61 I'd prefer `fourmolu` with these settings:

```
indentation: 2
comma-style: leading # 'leading' or 'trailing'
record-brace-space: true # rec {x = 1} vs. rec{x = 1}
indent-wheres: false
diff-friendly-import-export: false # 'false' uses Ormolu-style lists
respectful: false # don't be too opinionated about newlines etc.
haddock-style: multi-line
newlines-between-decls: 2
```

**Comment by kakkun61** [comment]
I'll make a PR about this after #31 will be merged.
