### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by kakkun61** [iand675/hs-opentelemetry#32]
I fixed CI errors in #31, so I want the main branch to be protected.

How do you think this? This repo's settings can be changed by only the repo owner @iand675.

- Require status checks before merging
  - I want
- Require pull request reviews before merging
  - If you want
- etc.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by iand675** [comment]
It is now protected, thanks for the suggestion
