### ISSUE TITLE
Instrumented application example?

### ISSUE THREAD

**Issue by peterstorm** [iand675/hs-opentelemetry#44]
Hello!

Just wondering if it would be possible to have a quick example of an instrumented application, in the examples? One that is not using any of the instrumentation libraries.

**Comment by peterstorm** [comment]
Also question.

When writing an instance for `MonadTracer` is it best practice to do as the yesod instrumentation does (though use `makeTracer` instead. I put the `Tracer` in our `Reader` env, but that is maybe bad practice?

```
instance MonadTracer (HandlerFor site) where
  getTracer = do
    tp <- getGlobalTracerProvider
    OpenTelemetry.Trace.Core.getTracer tp "hs-opentelemetry-instrumentation-yesod" tracerOptions
```

**Comment by iand675** [comment]
Hi Peter, I'm not sure I understand what you're asking for in the first question– you want to know how to use just the api/sdk for a very small app? I think you'll find that in the README here: https://hackage.haskell.org/package/hs-opentelemetry-sdk

Do let me know if that's not what you were hoping for.

**Comment by iand675** [comment]
Right now `getTracer` & `makeTracer` are quite cheap– they just read from an `IORef` and return the configuration read out of that as a datatype. It's marginally cheaper to use the monadic version _if you really need it_ to e.g. pull it from a reader monad, but either option runs in < 80ns generally, so you'd have to have a pretty specialized need to make it worthwhile.

**Comment by peterstorm** [comment]
Awesome! We instrumented an app now, and got to export to Datadog with unified logs and everything, so thank you for an awesome library 😄
