### ISSUE TITLE
improved postgresql-simple support

### ISSUE THREAD

**Issue by iand675** [iand675/hs-opentelemetry#7]

**Comment by magthe** [comment]
I thought I might take a stab at improving the support for postgresql-simple. As I'm rather new to the world of OpenTelemetry I thought I'd ask for a bit of a sanity check before I embark on this.

Based on https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/ I thought I'd first add instrumentation to one of the function in a personal project.

Does the following match your understanding of the convention as well?

```
insertEvent :: MonadIO m => Connection -> OE.Event -> m ()
insertEvent conn event = liftIO $ do
    connAttr <- staticConnectionAttributes conn
    statement <- formatQuery conn insertQuery $ OE.toDbEvent event
    dbName <- maybe "unknown db" TE.decodeUtf8 <$> withConnection conn LibPQ.db
    let callAttr = [("db.statement", toAttribute $ TE.decodeUtf8 statement)] :: [(T.Text, Attribute)]
        attrs = connAttr <> callAttr
        spanArgs = SpanArguments Client attrs [] Nothing
    tracerProvider <- getGlobalTracerProvider
    let tracer = makeTracer tracerProvider "gaboon.DB.insertEvent" tracerOptions
    inSpan tracer dbName spanArgs $
        void $ execute conn insertQuery $ OE.toDbEvent event
    void $ execute_ conn "NOTIFY gaboon"
  where
    insertQuery =
        [sql|
       INSERT INTO events
       (stream_id, cmd, cmd_id, correlation_id, event_data)
       VALUES (?, ?, ?, ?, ?)
       |]
```

**Comment by iand675** [comment]
That's pretty much right! Only thing I'd comment:

The tracer name should typically just be the name of your package or project (`gaboon`, I guess?)

**Comment by magthe** [comment]
The PR is awaiting review.
