### ISSUE TITLE
`hspec` combinators

### ISSUE THREAD

**Issue by parsonsmatt** [iand675/hs-opentelemetry#78]
I think we can get a better `hspec` integration by providing functions that use hspec hooks to do `inSpan` - example,

```haskell
-- | Like 'Hspec.describe' but creates a new 'Span' with the message.
describe :: HasCallStack => String -> SpecWith a -> SpecWith a
describe msg spec =
  aroundWith wrapSpec do
    withFrozenCallStack Hspec.describe msg spec
  where
    wrapSpec runTest a =
      inSpan (pack msg) defaultSpanArguments (runTest a)
```

Working on this locally, will figure out an extraction if it makes sense

**Comment by solomon-b** [comment]
Hi Matt. FYI, I went through hspec integration recently and rather then overload `describe` I opted to use `mapSpecForest` to modify the `SpecTree`. This allowed us to call `inSpan` on all our tests without having to modify the tests themselves.

**Comment by parsonsmatt** [comment]
Oh, that's a much nicer approach! Thanks for the tip.

**Comment by solomon-b** [comment]
Yup! That is incredibly similar to how I did it.

**Comment by iand675** [comment]
Thanks for the contribution :)
