### ISSUE TITLE
Release propagators-datadog

### ISSUE THREAD

**Issue by pbrisbin** [iand675/hs-opentelemetry#98]
Any plans to release https://github.com/iand675/hs-opentelemetry/tree/main/propagators/datadog ?

I've been able to get Datadog correlation fully working as far as I can tell by just adding a trace-id to my logs. The collector handles translating ids for traces, I guess, and then I just set my Trace ID field on log injecting, and it all matches up.

Thing is, I've had to in-line the bit fiddling though to do it, which I'd rather not. I'm not actually sure what a full-on Propagator will do for me, but I'd at least like to rely on the package for the bit-fiddler functions.

**Comment by kakkun61** [comment]
I am going to upload the package to Hackage, @iand675 is it OK?

**Comment by iand675** [comment]
Yes, sounds good!

Met vriendelijke groet,
Ian Duncan

**Comment by kakkun61** [comment]
Released https://hackage.haskell.org/package/hs-opentelemetry-propagator-datadog-0.0.0.0

**Comment by pbrisbin** [comment]
Thanks! Are there any docs on using non-default propagators? I.e. those not known [here](https://github.com/iand675/hs-opentelemetry/blob/main/sdk/src/OpenTelemetry/Trace.hs#L287-L294)?

**Comment by kakkun61** [comment]
Here is an example to create `TracerProvider` with a Datadog propagator.

```haskell
do
  otlpConfig <- loadExporterEnvironmentVariables
  exporter <- otlpExporter otlpConfig
  batchProcessorConfig <- detectBatchProcessorConfig
  processors <- (:[]) <$> batchProcessor batchProcessorConfig exporter
  (_, tracerProviderOptions) <- getTracerProviderInitializationOptions
  let tracerProviderOptions' =
        tracerProviderOptions
          { tracerProviderOptionsPropagators = datadogTraceContextPropagator
          }
  createTracerProvider processors tracerProviderOptions'
```
